// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPZT0xZmQXCYUwGupXE3Z8tb9fweAqNw',
    appId: '1:301118434296:web:8d9cf43e4bf044dc7e440d',
    messagingSenderId: '301118434296',
    projectId: 'progmobileflutter',
    authDomain: 'progmobileflutter.firebaseapp.com',
    storageBucket: 'progmobileflutter.appspot.com',
    measurementId: 'G-7FCQ5GCPES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRqyK7jwNsZVP4JJSWLroTO6YSiGz5wlU',
    appId: '1:301118434296:android:5c31981c00a8ffd07e440d',
    messagingSenderId: '301118434296',
    projectId: 'progmobileflutter',
    storageBucket: 'progmobileflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-h1xXeuUpBMQ_imhWH65fXXJc0TJiRuU',
    appId: '1:301118434296:ios:d313ea633b76f4da7e440d',
    messagingSenderId: '301118434296',
    projectId: 'progmobileflutter',
    storageBucket: 'progmobileflutter.appspot.com',
    iosClientId: '301118434296-3gu1sk3eig5j3ptgod63isaqupdjjrn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.progMobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-h1xXeuUpBMQ_imhWH65fXXJc0TJiRuU',
    appId: '1:301118434296:ios:68d0af5f9ff994757e440d',
    messagingSenderId: '301118434296',
    projectId: 'progmobileflutter',
    storageBucket: 'progmobileflutter.appspot.com',
    iosClientId: '301118434296-fb37kiev9fh26amuscb59nvm2p53dcq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.progMobileFlutter.RunnerTests',
  );
}
